apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
      annotations:
        k8s.v1.cni.cncf.io/networks: my-first-network, my-nginx-network
    spec:
      containers:
      - name: router
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeName: raspi3
